### ISSUE TITLE
Update ComponentsElectron for 3.0.0 Preview 3

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspLabs#177]
@SteveSandersonMS @mkArtakMSFT 

```
C:\Users\danroth27\Documents\GitHub\aspnet\AspLabs\src\ComponentsElectron\sample\SampleApp [master ≡]> dotnet run
[SampleApp:35436] out: Launching Electron on port 56690
Use Electron Port: 56690
[electron:28624] out:socket.io is listening on port 56690
[electron:28624] out:.NET Core Application connected...
BridgeConnector connected!
[SampleApp:35436] out: Waiting for interop connection
[SampleApp:35436] out: Interop connected
Attempt by method 'Microsoft.AspNetCore.Components.Electron.ElectronUriHelper.Initialize(System.String, System.String)' to access method 'Microsoft.JSInterop.JSRuntime.get_Current()' failed.
   at Microsoft.AspNetCore.Components.Electron.ElectronUriHelper.Initialize(String uriAbsolute, String baseUriAbsolute)
   at Microsoft.AspNetCore.Components.Electron.ComponentsElectron.<>c__DisplayClass0_0`1.<<Run>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Components.Electron.Launcher.<>c__DisplayClass12_0.<<StartElectronProcess>b__1>d.MoveNext()
```

**Comment by mkArtakMSFT** [comment]
Closing this as @SteveSandersonMS has done this already.
