### ISSUE TITLE
Error running a published "electron project" exe file outside project folder(using ComponentsElectron)

### ISSUE THREAD

**Issue by GoranHalvarsson** [aspnet/AspLabs#226]
I have successfully got a blazor-electron project running (using ComponentsElectron).
https://github.com/GoranHalvarsson/SitecoreBlazor/tree/master/SitecoreBlazorHosted.Electron

It all works well when running it from VisualStudio. It also works well when publishing it to the bin folder(within the project) and running the .exe file.

But if publishing outside the project folder it will not work. I get the following error:
``
Application: SitecoreBlazorHosted.Electron.exe
CoreCLR Version: 4.700.19.45506
.NET Core Version: 3.0.0-rc1-19456-20
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: Could not find any .csproj in or above 'D:\test\blazor\Electron'
   at Microsoft.AspNetCore.Components.Electron.Launcher.GetProjectRoot() in C:\Users\xxxxx\source\repos\AspLabs\src\ComponentsElectron\src\Microsoft.AspNetCore.Components.Electron\Launcher.cs:line 183
   at Microsoft.AspNetCore.Components.Electron.Launcher.StartElectronProcess(Func`1 callback) in C:\Users\xxxxx\source\repos\AspLabs\src\ComponentsElectron\src\Microsoft.AspNetCore.Components.Electron\Launcher.cs:line 31
   at Microsoft.AspNetCore.Components.Electron.ComponentsElectron.Run[TStartup](String hostJsPath) in C:\Users\xxxxx\source\repos\AspLabs\src\ComponentsElectron\src\Microsoft.AspNetCore.Components.Electron\ComponentsElectron.cs:line 52
   at SitecoreBlazorHosted.Electron.Program.Main(String[] args) in D:\Projects\SitecoreBlazor\SitecoreBlazorHosted.Electron\Program.cs:line 10
``

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're closing this issue as we're using `dotnet/AspNetCore` repo's issue tracker instead.
If you think this issue is still relevant, please file a new issue in that repo, so the team can triage it.
