### ISSUE TITLE
Exception thrown: The payload was invalid.

### ISSUE THREAD

**Issue by baer999** [aspnet/AspLabs#249]
When calling in App.razor file, I'm getting error (just on first Rendering).

Exception is thrown when calling:

AppState.BasketData = await ProtectedLocalStore.GetAsync<BasketState>($"Basket_{My.StoreId}") ?? new BasketState();

The Code is here:

` public class AppBase : ComponentBase
    {
        [Inject] protected AppState AppState { get; set; }
        [Inject] IJSRuntime JS { get; set; }
        [Inject] LocalStorageService LS { get; set; }

        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            try
            {
                using var tl = new TimeLogger($"App.razor OnAfterRenderAsync({firstRender})");

                if (firstRender)
                {
                    await LS.LoadBasket(AppState.StoreData?.MenuContainer);
                    StateHasChanged();
                }
            }
            catch (Exception ex)
            {
                My.Log.Error(ex);
            }
        }
    }

        public async Task LoadBasket(MenuDTO menu)
        {
            try
            {
                AppState.BasketData = await ProtectedLocalStore.GetAsync<BasketState>($"Basket_{My.StoreId}") ?? new BasketState();
            }
            catch (Exception ex)
            {
                My.Log.Error(ex);
            }
        }`

Then there is coming this error / stacktrace:

   at Microsoft.AspNetCore.DataProtection.Cng.CbcAuthenticatedEncryptor.DecryptImpl(Byte* pbCiphertext, UInt32 cbCiphertext, Byte* pbAdditionalAuthenticatedData, UInt32 cbAdditionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.Cng.Internal.CngAuthenticatedEncryptorBase.Decrypt(ArraySegment`1 ciphertext, ArraySegment`1 additionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Microsoft.AspNetCore.ProtectedBrowserStorage.ProtectedBrowserStorage.<GetAsync>d__10`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at PegasusV6.LocalStorageService.<LoadBasket>d__9.MoveNext() in C:\SOURCE\PegasusV6\PegasusV6\Services\LocalStorageService.cs:line 28

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We're closing this issue as we're using `dotnet/AspNetCore` repo's issue tracker instead.
If you think this issue is still relevant, please file a new issue in that repo, so the team can triage it.
